[tool.poetry]
name = "fetch-ai-test"
version = "0.1.0"
description = ""
authors = ["Raymond Allie <rsa85@cornell.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
uagents = "^0.16.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
